spring.application.name=SecretVaultAPI

spring.datasource.url=jdbc:postgresql://localhost:5050/{provide database name here}
spring.datasource.username=provide username
spring.datasource.password=provide password

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect